#[cfg(feature = "arr")]
pub mod arr;
#[cfg(feature = "bounds")]
pub mod bounds;
#[cfg(feature = "dsu")]
pub mod dsu;
#[cfg(feature = "fenwick")]
pub mod fenwick;
#[cfg(feature = "min_max")]
pub mod min_max;
#[cfg(feature = "segment_tree")]
pub mod segment_tree;
#[cfg(feature = "slice")]
pub mod slice;
#[cfg(feature = "sliding_window")]
pub mod sliding_window;